name: 'Terraform'

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: lint

    defaults:
      run:
        shell: bash

    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Format
      run: terraform fmt -check